spring:
  datasource:
    url: jdbc:mysql://localhost:3306/helloblog?setUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: mtt20091201wp
    driver-class-name: com.mysql.cj.jdbc.Driver

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8881/eureka/
