application:
  name: file
server:
  port: 8881

datasource:
  url: jdbc:mysql://localhost:3306/helloblog?setUnicode=true&characterEncoding=utf8
  username: root
  password: mtt20091201wp
  driver-class-name: com.mysql.jdbc.Driver

